Repository falcosecurity/client-go, pull requests merged in 2019-10, with the labels that each got.

#19 check error
  pkg/client/client.go
Labels: approved, area/client, dco-signoff: yes, kind/bug, lgtm, release-note, size/XS

#21 LICENSE
  LICENSE
Labels: approved, dco-signoff: yes, kind/documentation, kind/feature, lgtm, release-note-none, size/L

#22 update: grab proto from dev (fixes #18)
  Makefile
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, release-note, size/XS

#24 Request to be added to owners (approver/reviewer)
  OWNERS
Labels: approved, area/client, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS
