Repository falcosecurity/client-go, pull requests merged in 2019-09, with the labels that each got.

#8 docs: update readme to include examples
  README.md
Labels: approved, area/examples, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/M

#11 docs: godoc in readme
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, size/XS

#10 fix: move the client example into the client package
  pkg/client/example_test.go
Labels: approved, area/client, area/examples, area/tests, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS

#12 Request to be added to owners (approver/reviewer)
  OWNERS
Labels: approved, area/client, dco-signoff: yes, kind/cleanup, lgtm, release-note-none, size/XS
