Repository falcosecurity/client-go, pull requests merged in 2020-04, with the labels that each got.

#36 Add unit tests for client package
  Makefile
  README.md
  go.mod
  go.sum
  pkg/api/output/output.pb.go
  pkg/api/version/version.pb.go
  pkg/client/client.go
  pkg/client/client_test.go
Labels: approved, area/tests, dco-signoff: yes, kind/feature, lgtm, release-note-none, size/L

#41 docs(release.md): add release process instructions
  release.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, release-note-none, retest-not-required-docs-only, size/S

#42 fix(.circleci): add context for env vars
  .circleci/config.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, release-note-none, size/XS
